Add router
Mees100/Mees100.github.io pull request #6
Opened 2024-10-07 15:21 UTC by Mees100

alle pagina's zijn toegevoegd

2024-10-07 17:31 UTC, allartk requested changes
👍  1 kleinigheidje

2024-10-07 17:31 UTC, allartk commented on src/Bergen.jpg
4.47 MB, wellicht kan je de foto verkleinen tot de 400x400px zoals in de css.
Ook zou je hem kunnen verplaatsen naar een map src/images

2024-10-09 10:54 UTC, Mees100 commented on src/Bergen.jpg
gedaan

2024-10-09 11:06 UTC, allartk approved these changes

2024-10-13 14:10 UTC, merged